server:
   port: 80
  
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hiberante:
        format_sql: true
        use_sql_comments: true
        
logging.level:
  org.hibernate.SQL: debug
        
        